#!/bin/bash

# 1. Create a local folder for project-specific stubs
mkdir -p typings/gi

# 2. Generate Astal stubs into this folder
# (We point -o to ./typings to avoid polluting global python)
gengir Astal-4.0 -o ./typings/gi
gengir AstalWp-0.1 -o ./typings/gi
gengir AstalTray-0.1 -o ./typings/gi
gengir AstalPowerProfiles-0.1 -o ./typings/gi
gengir AstalNotifd-0.1 -o ./typings/gi
gengir AstalNiri-0.1 -o ./typings/gi
gengir AstalNetwork-0.1 -o ./typings/gi
gengir AstalMpris-0.1 -o ./typings/gi
gengir AstalIO-0.1 -o ./typings/gi
gengir AstalHyprland-0.1 -o ./typings/gi
gengir AstalGreet-0.1 -o ./typings/gi
gengir AstalCava-0.1 -o ./typings/gi
gengir AstalBluetooth-0.1 -o ./typings/gi
gengir AstalBattery-0.1 -o ./typings/gi
gengir AstalAuth-0.1 -o ./typings/gi
gengir AstalApps-0.1 -o ./typings/gi

# 3. CRITICAL: Delete the standard libs generated by gengir.
# We want VS Code to use the high-quality 'python-pygobject-stubs' for these,
# not the auto-generated ones.
# rm typings/gi/repository/Gtk.pyi
# rm typings/gi/repository/Gdk.pyi
# rm typings/gi/repository/Gio.pyi
# rm typings/gi/repository/GObject.pyi
# rm typings/gi/repository/GLib.pyi
# rm typings/gi/repository/Pango.pyi
# rm typings/gi/repository/cairo.pyi
# rm typings/gi/repository/HarfBuzz.pyi
# rm typings/gi/repository/freetype2.pyi

# 4. Reinstall system stubs (just to be safe)
paru -S --rebuild python-pygobject-stubs
